# fly.toml app configuration file generated for sea-cinema on 2023-07-06T12:38:54+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sea-cinema"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
